<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>GastricCancerDetection.API</RootNamespace>
    <UserSecretsId>gastric-cancer-detection-api</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GastricCancerDetection.Infrastructure\GastricCancerDetection.Infrastructure.csproj" />
  </ItemGroup>
</Project>
