"""Reference-aware VCF normalization utilities for WGR-CDP.

The normalizer is dependency-free and intentionally conservative:
- requires an explicit reference FASTA for biological normalization;
- validates REF against the reference sequence;
- minimally trims common bases;
- left-aligns simple insertions/deletions in repeat contexts;
- preserves provenance in INFO and audit metadata;
- uses a .fai-style index for scalable random access to large FASTA files;
- never claims normalization when the reference is unavailable or mismatched.
"""
from __future__ import annotations

from pathlib import Path
import hashlib


UNAVAILABLE = "Data unavailable"


def read_fasta(path):
    """Load a small/medium FASTA into a chromosome -> sequence mapping.

    Kept for tests and small reference fixtures. Production normalization uses
    :class:`IndexedFastaReference` to avoid loading the whole human genome.
    """
    sequences = {}
    name = None
    chunks = []
    with Path(path).open("r", encoding="utf-8") as handle:
        for raw in handle:
            line = raw.strip()
            if not line:
                continue
            if line.startswith(">"):
                if name is not None:
                    sequences[name] = "".join(chunks).upper()
                name = line[1:].split()[0]
                chunks = []
            else:
                if name is None:
                    raise ValueError("FASTA sequence encountered before a header")
                chunks.append(line)
    if name is not None:
        sequences[name] = "".join(chunks).upper()
    if not sequences:
        raise ValueError("Reference FASTA contains no sequences")
    return sequences


class IndexedFastaReference:
    """Lazy random-access FASTA reader using a standard FAI-like index.

    The FASTA must be uncompressed. When `<reference>.fai` is missing, a
    deterministic index is generated by scanning the FASTA once.
    """

    def __init__(self, path):
        self.path = Path(path)
        if not self.path.exists():
            raise ValueError(f"Reference FASTA does not exist: {self.path}")
        if self.path.suffix == ".gz":
            raise ValueError(
                "Compressed FASTA is not supported for indexed random access; "
                "decompress the reference first."
            )
        self.index_path = Path(str(self.path) + ".fai")
        if not self.index_path.exists():
            build_fasta_index(self.path, self.index_path)
        self.index = _read_fai(self.index_path)
        if not self.index:
            raise ValueError(f"Reference FASTA index is empty: {self.index_path}")
        self._handle = None
        self.sha256 = _sha256(self.path)

    def resolve_chrom(self, chrom):
        chrom = str(chrom)
        aliases = [chrom]
        if chrom.startswith("chr"):
            aliases.append(chrom[3:])
        else:
            aliases.append("chr" + chrom)
        for alias in aliases:
            if alias in self.index:
                return alias
        return None

    def fetch(self, chrom, start, end):
        """Fetch a zero-based half-open interval."""
        if start < 0 or end < start:
            raise ValueError("Invalid FASTA fetch interval")
        resolved = self.resolve_chrom(chrom)
        if resolved is None:
            return None
        length, offset, line_bases, line_width = self.index[resolved]
        if end > length:
            return None
        if start == end:
            return ""
        if self._handle is None:
            self._handle = self.path.open("rb")
        chunks = []
        position = start
        remaining = end - start
        while remaining:
            line_index, in_line = divmod(position, line_bases)
            byte_offset = offset + line_index * line_width + in_line
            take = min(remaining, line_bases - in_line)
            self._handle.seek(byte_offset)
            chunk = self._handle.read(take)
            if len(chunk) != take:
                return None
            chunks.append(chunk.decode("ascii"))
            position += take
            remaining -= take
        return "".join(chunks).upper()

    def close(self):
        if self._handle is not None:
            self._handle.close()
            self._handle = None

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb):
        self.close()


def _read_fai(path):
    index = {}
    with Path(path).open("r", encoding="utf-8") as handle:
        for raw in handle:
            fields = raw.rstrip("\r\n").split("\t")
            if len(fields) != 5:
                raise ValueError(f"Invalid FASTA index row: {raw.rstrip()}")
            name, length, offset, line_bases, line_width = fields
            index[name] = (
                int(length), int(offset), int(line_bases), int(line_width)
            )
    return index


def build_fasta_index(fasta_path, index_path=None):
    """Build a deterministic FAI-style index for an uncompressed FASTA."""
    fasta_path = Path(fasta_path)
    index_path = Path(index_path or str(fasta_path) + ".fai")
    current = None
    length = 0
    offset = None
    line_bases = None
    line_width = None
    rows = []

    with fasta_path.open("rb") as handle:
        while True:
            line_offset = handle.tell()
            raw = handle.readline()
            if not raw:
                break
            stripped = raw.rstrip(b"\r\n")
            if not stripped:
                continue
            if raw.startswith(b">"):
                if current is not None:
                    rows.append(
                        (current, length, offset, line_bases, line_width)
                    )
                current = raw[1:].strip().split(None, 1)[0].decode("ascii")
                length = 0
                offset = None
                line_bases = None
                line_width = None
                continue
            if current is None:
                raise ValueError("FASTA sequence encountered before a header")
            if offset is None:
                offset = line_offset
                line_bases = len(stripped)
                line_width = len(raw)
            elif len(stripped) != line_bases:
                # Only the final line of a contig may be shorter than the
                # established FASTA line width.
                if len(stripped) > line_bases:
                    raise ValueError(
                        f"Inconsistent FASTA line width for contig {current}"
                    )
            length += len(stripped)

    if current is not None:
        rows.append((current, length, offset, line_bases, line_width))

    if not rows:
        raise ValueError("Reference FASTA contains no sequences")

    index_path.parent.mkdir(parents=True, exist_ok=True)
    with index_path.open("w", encoding="utf-8", newline="") as handle:
        for row in rows:
            handle.write("\t".join(map(str, row)) + "\n")
    return index_path


def _sha256(path, chunk_size=1024 * 1024):
    digest = hashlib.sha256()
    with Path(path).open("rb") as handle:
        for chunk in iter(lambda: handle.read(chunk_size), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _resolve_chrom(reference, chrom):
    if hasattr(reference, "resolve_chrom"):
        return reference.resolve_chrom(chrom)
    chrom = str(chrom)
    aliases = [chrom]
    if chrom.startswith("chr"):
        aliases.append(chrom[3:])
    else:
        aliases.append("chr" + chrom)
    for alias in aliases:
        if alias in reference:
            return alias
    return None


def _fetch(reference, chrom, start, end):
    if hasattr(reference, "fetch"):
        return reference.fetch(chrom, start, end)
    return reference[chrom][start:end].upper()


def _trim(ref, alt, pos):
    # Keep at least one anchor base in each allele.
    while len(ref) > 1 and len(alt) > 1 and ref[0] == alt[0]:
        ref = ref[1:]
        alt = alt[1:]
        pos += 1
    while len(ref) > 1 and len(alt) > 1 and ref[-1] == alt[-1]:
        ref = ref[:-1]
        alt = alt[:-1]
    return ref, alt, pos


def _left_align_indel(reference, chrom, ref, alt, pos):
    # VCF POS is 1-based. For a simple insertion/deletion, the variant can
    # move left through a repeat when the altered allele contains the same
    # terminal base as the immediately preceding reference base.
    while pos > 1 and len(ref) != len(alt):
        prev = _fetch(reference, chrom, pos - 2, pos - 1)
        if not prev:
            break
        prev = prev[0]
        if len(ref) < len(alt):
            if alt[-1] != prev:
                break
            pos -= 1
            ref = prev
            alt = prev + alt[:-1]
        else:
            if ref[-1] != prev:
                break
            pos -= 1
            ref = prev + ref[:-1]
            alt = prev
        ref, alt, pos = _trim(ref, alt, pos)
    return ref, alt, pos


def normalize_variant(record, reference=None, strict_reference=True):
    """Normalize one VCF record against a reference.

    Returns a new record plus audit fields. One ALT allele is normalized at a
    time, so callers can safely expand multiallelic records.
    """
    required = ("chrom", "pos", "ref", "alt")
    missing = [key for key in required if key not in record]
    if missing:
        raise ValueError(f"Missing variant fields: {', '.join(missing)}")

    chrom = str(record["chrom"])
    pos = int(record["pos"])
    ref = str(record["ref"]).upper()
    raw_alt = record["alt"]

    # Preserve the original public helper contract when no reference is
    # supplied: a multiallelic ALT list remains a list and only stable
    # canonical casing/coordinate types are returned.
    if reference is None:
        if isinstance(raw_alt, (list, tuple)):
            alt = [str(allele).upper() for allele in raw_alt]
        else:
            alt = str(raw_alt).upper()
        return {
            "chrom": chrom,
            "pos": pos,
            "ref": ref,
            "alt": alt,
        }

    alt = str(raw_alt).upper()
    if pos < 1 or not ref or not alt:
        raise ValueError("Invalid variant coordinates or alleles")

    result = dict(record)
    result.update({
        "chrom": chrom,
        "pos": pos,
        "ref": ref,
        "alt": alt,
        "normalization_status": "reference_aware",
    })

    ref_chrom = _resolve_chrom(reference, chrom)
    if ref_chrom is None:
        result["normalization_status"] = UNAVAILABLE
        result["reference_validation"] = "chromosome_not_found"
        return result

    start0 = pos - 1
    observed = _fetch(reference, ref_chrom, start0, start0 + len(ref))
    if observed is None or len(observed) != len(ref):
        result["normalization_status"] = UNAVAILABLE
        result["reference_validation"] = "reference_interval_out_of_bounds"
        return result

    if observed != ref:
        result["reference_validation"] = "mismatch"
        result["normalization_status"] = "reference_mismatch"
        if strict_reference:
            return result
        return result

    norm_ref, norm_alt, norm_pos = _trim(ref, alt, pos)
    if len(norm_ref) != len(norm_alt):
        norm_ref, norm_alt, norm_pos = _left_align_indel(
            reference, ref_chrom, norm_ref, norm_alt, norm_pos
        )
        norm_ref, norm_alt, norm_pos = _trim(norm_ref, norm_alt, norm_pos)

    final_ref = _fetch(
        reference,
        ref_chrom,
        norm_pos - 1,
        norm_pos - 1 + len(norm_ref),
    )
    if final_ref != norm_ref:
        result["normalization_status"] = "normalization_validation_failed"
        result["reference_validation"] = "normalized_ref_mismatch"
        return result

    result.update({
        "pos": norm_pos,
        "ref": norm_ref,
        "alt": norm_alt,
        "reference_validation": "match",
    })
    return result


def _add_info(info, key, value):
    items = [item for item in str(info or ".").split(";") if item and item != "."]
    items.append(f"{key}={value}")
    return ";".join(items)


def normalize_vcf(
    input_path,
    output_path,
    reference_fasta,
    reference_build="GRCh38",
    reference=None,
):
    """Normalize a dependency-free VCF with an explicit FASTA reference.

    `reference` may be an already-open IndexedFastaReference to avoid
    re-reading/re-indexing the reference during batch operations.
    """
    from wgr_cdp.data_ingestion.vcf import read_vcf

    own_reference = reference is None
    ref_obj = reference or IndexedFastaReference(reference_fasta)
    records = read_vcf(input_path)
    expanded = []
    status_counts = {}

    for record in records:
        for alt in record.get("alt") or []:
            normalized = normalize_variant(
                {**record, "alt": str(alt).upper()},
                reference=ref_obj,
                strict_reference=True,
            )
            normalized["id"] = record.get("id")
            normalized["info"] = _add_info(
                record.get("info", "."),
                "WGR_NORM",
                normalized["normalization_status"],
            )
            normalized["info"] = _add_info(
                normalized["info"],
                "WGR_REF_CHECK",
                normalized["reference_validation"],
            )
            normalized["info"] = _add_info(
                normalized["info"],
                "WGR_ORIG",
                f"{record['chrom']}:{int(record['pos'])}:{record['ref']}:{alt}",
            )
            expanded.append(normalized)
            status = normalized["normalization_status"]
            status_counts[status] = status_counts.get(status, 0) + 1

    # Deduplicate after normalization and sort deterministically.
    unique = {}
    for row in expanded:
        key = (row["chrom"], row["pos"], row["ref"], row["alt"])
        unique.setdefault(key, row)
    outputs = sorted(
        unique.values(),
        key=lambda row: (
            str(row["chrom"]),
            int(row["pos"]),
            str(row["ref"]),
            str(row["alt"]),
        ),
    )

    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    headers = [
        "##fileformat=VCFv4.2",
        "##source=WGR-CDP_reference_aware_normalizer",
        f"##reference={reference_build}",
        "##wgr_cdp_normalization_status=reference_aware",
        '##INFO=<ID=WGR_NORM,Number=1,Type=String,Description="WGR-CDP normalization status">',
        '##INFO=<ID=WGR_REF_CHECK,Number=1,Type=String,Description="WGR-CDP reference validation status">',
        '##INFO=<ID=WGR_ORIG,Number=1,Type=String,Description="Original variant before normalization">',
        "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO",
    ]
    with out.open("w", encoding="utf-8", newline="") as handle:
        handle.write("\n".join(headers) + "\n")
        for row in outputs:
            handle.write("\t".join([
                str(row["chrom"]),
                str(row["pos"]),
                "." if row.get("id") in (None, "") else str(row["id"]),
                str(row["ref"]),
                str(row["alt"]),
                "." if row.get("qual") in (None, "") else str(row["qual"]),
                str(row.get("filter") or "PASS"),
                str(row.get("info") or "."),
            ]) + "\n")

    mismatch = status_counts.get("reference_mismatch", 0)
    unavailable = sum(
        count for status, count in status_counts.items()
        if status in {UNAVAILABLE, "normalization_validation_failed"}
    )
    ref_hash = getattr(ref_obj, "sha256", None)
    if ref_hash is None and isinstance(ref_obj, dict):
        ref_hash = _sha256(reference_fasta)

    result = {
        "schema_version": "A13-NORMALIZATION-1",
        "status": (
            "PASS"
            if outputs and mismatch == 0 and unavailable == 0
            else "FAIL"
            if mismatch > 0
            else "CONDITIONAL"
        ),
        "input_file": str(input_path),
        "output_file": str(out),
        "reference_fasta": str(reference_fasta),
        "reference_build": reference_build,
        "input_record_count": len(records),
        "expanded_record_count": len(expanded),
        "deduplicated_record_count": len(outputs),
        "status_counts": status_counts,
        "reference_mismatch_count": mismatch,
        "reference_fasta_sha256": ref_hash,
        "reference_index": str(getattr(ref_obj, "index_path", UNAVAILABLE)),
        "normalization_required": False,
    }

    if own_reference:
        ref_obj.close()
    return result


def normalize_vcf_batch(input_dir, output_dir, reference_fasta, pattern="*.vcf", reference_build="GRCh38"):
    """Normalize a VCF directory while reusing one indexed reference object."""
    input_dir = Path(input_dir)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    sources = sorted(input_dir.glob(pattern))
    if not sources:
        return {
            "schema_version": "A13-NORMALIZATION-BATCH-1",
            "status": "Data unavailable",
            "input_dir": str(input_dir),
            "output_dir": str(output_dir),
            "reference_fasta": str(reference_fasta),
            "input_file_count": 0,
            "normalized_file_count": 0,
            "input_record_count": 0,
            "expanded_record_count": 0,
            "deduplicated_record_count": 0,
            "reference_mismatch_count": 0,
            "conditional_file_count": 0,
            "results": [],
        }

    ref_obj = IndexedFastaReference(reference_fasta)
    try:
        results = []
        for source in sources:
            output = output_dir / source.name
            results.append(
                normalize_vcf(
                    source,
                    output,
                    reference_fasta,
                    reference_build=reference_build,
                    reference=ref_obj,
                )
            )
    finally:
        ref_obj.close()

    mismatch = sum(item.get("reference_mismatch_count", 0) for item in results)
    conditional = sum(1 for item in results if item.get("status") != "PASS")
    status = (
        "PASS"
        if results and conditional == 0
        else "FAIL"
        if mismatch > 0
        else "CONDITIONAL"
    )
    payload = {
        "schema_version": "A13-NORMALIZATION-BATCH-1",
        "status": status,
        "input_dir": str(input_dir),
        "output_dir": str(output_dir),
        "reference_fasta": str(reference_fasta),
        "reference_build": reference_build,
        "input_file_count": len(sources),
        "normalized_file_count": sum(
            1 for item in results if item.get("status") == "PASS"
        ),
        "input_record_count": sum(item.get("input_record_count", 0) for item in results),
        "expanded_record_count": sum(item.get("expanded_record_count", 0) for item in results),
        "deduplicated_record_count": sum(
            item.get("deduplicated_record_count", 0) for item in results
        ),
        "reference_mismatch_count": mismatch,
        "conditional_file_count": conditional,
        "reference_fasta_sha256": ref_obj.sha256,
        "reference_index": str(ref_obj.index_path),
        "results": results,
    }
    return payload
